stages:
    - test
    - development
    - production_icommits
    - production_sman21
    - production_sman5
    
test_branch:
    stage: test
    script: echo proses berjalan
    script: echo proses runner berjalan
    
development_branch:
    stage: development
    only: 
        - development
    script:
        - cd /var/www/html/globaltech-codeigniter
        - git reset --hard
        - git pull origin development
        - sudo rm /var/www/globaltech-codeigniter/application/config/database.php
        - cp /var/www/globaltech-codeigniter/database/config/database1.php /var/www/globaltech-codeigniter/application/config/database.php
        - sudo rm /var/www/globaltech-codeigniter/application/config/config.php
        - cp /var/www/globaltech-codeigniter/database/config/config.php /var/www/globaltech-codeigniter/application/config/config.php
        
production_icommits:
    stage: production_icommits
    only: 
        - production_icommits
    script:
        - cd /var/www/globaltech-codeigniter
        - git reset --hard
        - git pull origin production_icommits
        - sudo rm /var/www/globaltech-codeigniter/application/config/database.php
        - sudo cp /var/www/globaltech-codeigniter/database/config1/database1.php /var/www/globaltech-codeigniter/application/config/database.php
        - sudo rm /var/www/globaltech-codeigniter/application/config/config.php
        - sudo cp /var/www/globaltech-codeigniter/database/config1/config.php /var/www/globaltech-codeigniter/application/config/config.php
        
production_sman21:
    stage: production_sman21
    only: 
        - production_sman21
    script:
        - cd /var/www/globaltech-codeigniter
        - git reset --hard
        - git pull origin production_sman21
        - sudo rm /var/www/globaltech-codeigniter/application/config/database.php
        - sudo cp /var/www/globaltech-codeigniter/database/config1/database1.php /var/www/globaltech-codeigniter/application/config/database.php
        - sudo rm /var/www/globaltech-codeigniter/application/config/config.php
        - sudo cp /var/www/globaltech-codeigniter/database/config1/config.php /var/www/globaltech-codeigniter/application/config/config.php
        
production_sman5:
    stage: production_sman5
    only: 
        - production_sman5
    script:
        - cd /var/www/globaltech-codeigniter
        - git reset --hard
        - git pull origin production_sman5
        - sudo rm /var/www/globaltech-codeigniter/application/config/database.php
        - sudo cp /var/www/globaltech-codeigniter/database/config1/database1.php /var/www/globaltech-codeigniter/application/config/database.php
        - sudo rm /var/www/globaltech-codeigniter/application/config/config.php
        - sudo cp /var/www/globaltech-codeigniter/database/config1/config.php /var/www/globaltech-codeigniter/application/config/config.php