stages:
    - test
    - development
    - production
    
test_branch:
    stage: test
    script: echo proses berjalan
    
development_branch:
    stage: development
    only: 
        - development
    script:
        - cd /var/www/html/tnial-codeigniter
        - git reset --hard
        - git pull origin development
        
production_branch:
    stage: production
    only: 
        - production
    script:
        - cd /var/www/tnial-codeigniter
        - git reset --hard
        - git pull origin production
