stages:
    - test
    - development
    - production
    
test_branch:
    stage: test
    script: echo proses berjalan
    script: echo proses runner berjalan
    
development_branch:
    stage: development
    only: 
        - development
    script:
        - cd /var/www/html/globaltech-codeigniter
        - git reset --hard
        - git pull origin development
        - sudo chmod 777 -R /var/www/html/globaltech-codeigniter
        
production_branch:
    stage: production
    only: 
        - production
    script:
        - cd /var/www/globaltech-codeigniter
        - git reset --hard
        - git pull origin production
        - sudo chmod 777 -R /var/www/globaltech-codeigniter