stages:
    - test
    - development
    - production
    
test_branch:
    stage: test
    script: echo proses berjalan
    
development_branch:
    stage: development
    only: 
        - development
    script:
        - cd /var/www/html/globaltech-codeigniter
        - git checkout development
        - git pull
        
production_branch:
    stage: production
    only: 
        - production
    script:
        - cd /var/www/globaltech-codeigniter
        - git checkout production
        - git pull